Fri Oct 25 18:13:16 UTC 2024
a/mkinitrd-1.4.11-x86_64-40.txz:  Rebuilt.
  remove-orphaned-initrds: also remove dangling initrd symlinks.
l/glib2-2.82.2-x86_64-2.txz:  Rebuilt.
  Removed useless symlinks. Thanks to marav.
l/mozilla-nss-3.106-x86_64-1.txz:  Upgraded.
x/xterm-395-x86_64-1.txz:  Upgraded.

diff --git a/source/k/kernel-source.SlackBuild b/source/k/kernel-source.SlackBuild
--- a/source/k/kernel-source.SlackBuild
+++ b/source/k/kernel-source.SlackBuild
@@ -33,17 +33,11 @@ CONFIG_PREEMPT_DEFAULT_MODE=${CONFIG_PREEMPT_DEFAULT_MODE:-voluntary}
 
 # If a $VERSION is not passed to this script, use the newest linux-*.tar.xz
 # found in this directory:
-VERSION=${VERSION:-$(/bin/ls -t linux-*.tar.?z | head -n 1 | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+VERSION=${VERSION:-$(/bin/ls -t linux-*.tar.?z | head -n 1 | rev | cut -f 3- -d . | rev | cut -f2- -d -)}
 if ! /bin/ls linux-*.tar.?z 1> /dev/null 2> /dev/null ; then
   echo "Error: kernel source not found. (/bin/ls linux-*.tar.?z)"
-fi
-
-# Automatically determine the architecture we're building on:
-if [ -z "$ARCH" ]; then
-  case "$(uname -m)" in
-    # Use uname -m for all archs:
-    *) ARCH=$(uname -m) ;;
-  esac
+else
+  USINGVER="Using kernel source linux-${VERSION}.tar.xz."
 fi
 
 # This function will revert or apply patches that are present here.
@@ -94,9 +88,51 @@ apply_patches() {
   fi
 }
 
-# If KERNEL_CONFIG (name of kernel .config file in ./kernel-configs to use)
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  # We will have to extract and patch the kernel sources to find out the kernel version:
+  TEMPDIR=$(mktemp -d)
+  cd $TEMPDIR
+  tar xf $CWD/linux-${VERSION}.tar.?z || exit 1
+  cd linux-*
+  apply_patches
+  PACKAGE_VERSION=$(grep "^VERSION = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^PATCHLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^SUBLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev)$(grep "^EXTRAVERSION = " Makefile | rev | cut -f 1 -d ' ' | rev)
+  cd $CWD
+  rm -rf $TEMPDIR
+  # No $LOCALVERSION
+  echo "kernel-source-$(echo ${PACKAGE_VERSION} | tr - _)-noarch-$BUILD.txz"
+  exit 0    
+fi
+
+echo $USINGVER
+
+# If we were not given a KERNEL_NAME, use generic:
+KERNEL_NAME=${KERNEL_NAME:-generic}
+
+# By default, we'll try to find a kernel config file. Otherwise, you can pass
+# KERNEL_CONFIG=some_kernel_config_file to this script. If KERNEL_CONFIG starts
+# with a '/', we'll assume it's a full absolute path to the kernel config file.
+# Otherwise we'll look for it in $KERNEL_CONFIGDIR (defined below).
+
+# Where should we find the kernel config files?
+KERNEL_CONFIGDIR=${KERNEL_CONFIGDIR:-./kernel-configs}
+
+# Make KERNEL_CONFIGDIR an absolute path:
+KERNEL_CONFIGDIR=$(realpath $KERNEL_CONFIGDIR)
+
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$(uname -m)" in
+    # Use uname -m for all archs:
+    *) ARCH=$(uname -m) ;;
+  esac
+fi
+
+# If KERNEL_CONFIG (name of kernel .config file in $KERNEL_CONFIGDIR to use)
 # has not been passed to this script, then we will select one. We will prefer
-# to use a generic, SMP-supporting .config with a version number exactly
+# to use a .config that matches KERNEL_NAME and with a version number exactly
 # matching the kernel sources. But if there's no exact version match, we will
 # start with the newest .config we can find that's of the appropriate type.
 if [ -z "${KERNEL_CONFIG}" ]; then # figure out the best matching .config
@@ -107,47 +143,59 @@ if [ -z "${KERNEL_CONFIG}" ]; then # figure out the best matching .config
   elif [ "$ARCH" = "i686" ]; then
     CONFIG_SUFFIX=".ia32"
   fi
-  if [ -r "$CWD/kernel-configs/config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX}" ]; then
+  if [ -r "$KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}" ]; then
     # Exact match!
-    KERNEL_CONFIG="config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX}"
+    KERNEL_CONFIG="config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}"
   else # no exact match, so find newest with the same name:
-    FIND_MATCH="$(/bin/ls -t $CWD/kernel-configs/config-*${LOCALVERSION}-generic${CONFIG_SUFFIX} 2> /dev/null | head -n 1)"
+    FIND_MATCH="$(/bin/ls -t $KERNEL_CONFIGDIR/config-*${KERNEL_NAME}${CONFIG_SUFFIX} 2> /dev/null | head -n 1)"
     if [ -r "${FIND_MATCH}" ]; then
       KERNEL_CONFIG="$(basename ${FIND_MATCH})"
       unset FIND_MATCH
     else
-      echo "Error: no matching .config file could be found for this kernel. Tried:"
-      echo "  $CWD/kernel-configs/config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX} (not found)" 
-      exit 1
+      # We'll try to fall back on a defconfig if there's one for this $ARCH:
+      if [ "$ARCH" = "x86_64" ]; then
+        echo "WARNING:"
+        echo "Tried and did not find:"
+        echo "  $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}"
+        echo "Also could not match this fallback:"
+        echo "  $KERNEL_CONFIGDIR/config-*-${KERNEL_NAME}${CONFIG_SUFFIX}"
+        KERNEL_CONFIGDIR=$PKG/usr/src/linux/arch/x86/configs
+        KERNEL_CONFIG=x86_64_defconfig
+        KERNEL_NAME=defconfig
+        echo "Falling back on $KERNEL_CONFIGDIR/$KERNEL_CONFIG because we couldn't find anything better."
+        sleep 10
+      elif uname -m | grep -q i.86 ; then
+        echo "WARNING:"
+        echo "Tried and did not find:"
+        echo "  $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}"
+        echo "Also could not match this fallback:"
+        echo "  $KERNEL_CONFIGDIR/config-*-${KERNEL_NAME}${CONFIG_SUFFIX}"
+        KERNEL_CONFIGDIR=$PKG/usr/src/linux/arch/x86/configs
+        KERNEL_CONFIG=i386_defconfig
+        KERNEL_NAME=defconfig
+        echo "Falling back on $KERNEL_CONFIGDIR/$KERNEL_CONFIG because we couldn't find anything better."
+        sleep 10
+      else
+        echo "Error: no matching .config file could be found for this kernel. Tried:"
+        echo "  $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX} (not found)" 
+        exit 1
+      fi
     fi 
   fi
 else # We were given a name to use:
-  if [ ! -r "$CWD/kernel-configs/${KERNEL_CONFIG}" ]; then
-    echo "Error: specified kernel .config $CWD/kernel-configs/${KERNEL_CONFIG} was not found."
+  if [ "$(echo ${KERNEL_CONFIG} | cut -b 1)" = "/" ]; then # absolute path, split this:
+    KERNEL_CONFIGDIR=$(dirname ${KERNEL_CONFIG})
+    KERNEL_CONFIG=$(basename ${KERNEL_CONFIG})
+  fi
+  if [ ! -r "$KERNEL_CONFIGDIR/${KERNEL_CONFIG}" ]; then
+    echo "Error: specified kernel .config $KERNEL_CONFIGDIR/${KERNEL_CONFIG} was not found."
     exit 1
   fi
 fi
 # Set LOCALVERSION to the value found inside the .config:
-LOCALVERSION="$(cat $CWD/kernel-configs/${KERNEL_CONFIG} | grep CONFIG_LOCALVERSION= | cut -f 2 -d = | tr -d \")"
+LOCALVERSION="$(cat $KERNEL_CONFIGDIR/${KERNEL_CONFIG} | grep CONFIG_LOCALVERSION= | cut -f 2 -d = | tr -d \")"
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
-if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
-  # We will have to extract and patch the kernel sources to find out the kernel version:
-  TEMPDIR=$(mktemp -d)
-  cd $TEMPDIR
-  tar xf $CWD/linux-${VERSION}.tar.?z || exit 1
-  cd linux*
-  apply_patches
-  PACKAGE_VERSION=$(grep "^VERSION = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^PATCHLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^SUBLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev)$(grep "^EXTRAVERSION = " Makefile | rev | cut -f 1 -d ' ' | rev)
-  cd $CWD
-  rm -rf $TEMPDIR
-  echo "kernel-source-$(echo ${PACKAGE_VERSION} | tr - _)$(echo ${LOCALVERSION} | tr - _)-noarch-$BUILD.txz"
-  exit 0    
-fi
-
-echo "Using kernel config: $CWD/kernel-configs/${KERNEL_CONFIG}"
+echo "Using kernel config: $KERNEL_CONFIGDIR/${KERNEL_CONFIG}"
 
 rm -rf $PKG
 mkdir -p $TMP $PKG
@@ -160,8 +208,8 @@ echo "Untarring $CWD/linux-${VERSION}.tar.?z in $PKG/usr/src..."
   ln -sf linux-* linux
   cd linux-*
   apply_patches VERBOSE
-  echo "Copying $CWD/kernel-configs/${KERNEL_CONFIG} to .config..."
-  cp -a $CWD/kernel-configs/${KERNEL_CONFIG} .config
+  echo "Copying $KERNEL_CONFIGDIR/${KERNEL_CONFIG} to .config..."
+  cp -a $KERNEL_CONFIGDIR/${KERNEL_CONFIG} .config
   echo "Fixing permissions/ownership..."
   chown -R root:root .
   find . \
@@ -175,12 +223,25 @@ echo "Untarring $CWD/linux-${VERSION}.tar.?z in $PKG/usr/src..."
 # the installed kernel source package is fully configured, and building an
 # out-of-tree module (such as the NVIDIA driver) won't require the user
 # to build the kernel sources first.
-( cd $PKG/usr/src/linux-${VERSION}
+( cd $PKG/usr/src/linux-*
   echo "Making oldconfig..."
   make oldconfig
-  if [ ! -r $CWD/kernel-configs/config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX} ]; then
-    echo "Saving new .config as: $CWD/kernel-configs/config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX}"
-    cp -a .config $CWD/kernel-configs/config-${VERSION}${LOCALVERSION}-generic${CONFIG_SUFFIX}
+  if [ ! -r $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX} ]; then
+    # If you care about saving the original unregenerated unrenamed config
+    # file, set SAVE_ORIGINAL_KERNEL_CONFIG to something. This might cause
+    # your kernels to be built twice...
+    if [ -z "$SAVE_ORIGINAL_KERNEL_CONFIG" ]; then
+      echo "Removing original .config $KERNEL_CONFIGDIR/${KERNEL_CONFIG}"
+      rm -v -f $KERNEL_CONFIGDIR/${KERNEL_CONFIG}
+    fi
+    echo "Saving new .config as: $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}"
+    cp -a .config $KERNEL_CONFIGDIR/config-${VERSION}${LOCALVERSION}-${KERNEL_NAME}${CONFIG_SUFFIX}
+
+    # If we see ONLY_STAGE_KERNEL_SOURCE=yes, then we don't want to build this.
+    # We're just setting it up for use by the other SlackBuilds.
+    if [ "$ONLY_STAGE_KERNEL_SOURCE" = "yes" ]; then
+      exit 0
+    fi
   fi
 
   # If CONFIG_PREEMPT=y and CONFIG_PREEMPT_DYNAMIC=y, then set a default preempt
@@ -211,17 +272,41 @@ echo "Untarring $CWD/linux-${VERSION}.tar.?z in $PKG/usr/src..."
   find . -name "*.cmd" -exec rm -f "{}" \+ 
   rm .*.d
   # Still some dotfiles laying around... probably fine though
+  # Get rid of any ELF (non-eBPF) binaries:
+  find . -type f | xargs file | grep ELF | grep -v eBPF | grep stripped | cut -f 1 -d : | while read elf_binary ; do
+    rm -f -v $elf_binary
+  done 
 ) || exit 1
 
-cd $PKG/usr/src/linux-${VERSION}
+# Just staging the sources? Then leave.
+if [ "$ONLY_STAGE_KERNEL_SOURCE" = "yes" ]; then
+  exit 0
+fi
+
+cd $PKG/usr/src/linux-*
 # Use the version number found in the Makefile in the package name. This is not
 # always the same as the version in the source tarball's filename. For example,
 # linux-4.14.tar.xz will have 4.14.0 as the version in the Makefile:
 PACKAGE_VERSION=$(grep "^VERSION = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^PATCHLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev).$(grep "^SUBLEVEL = " Makefile | rev | cut -f 1 -d ' ' | rev)$(grep "^EXTRAVERSION = " Makefile | rev | cut -f 1 -d ' ' | rev)
 
+## This might be a bit too harsh... ;-)
+## The .config we built with is irrelevant, but set KEEPCONFIG to anything
+## if you want to keep it:
+#if [ -z "$KEEPCONFIG" ]; then
+#  rm .config*
+#fi
+
+# Make sure the directory and symlink are properly named:
+cd ..
+rm -f linux
+# LOCALVERSION is part of the .config, not really the sources. We're not going
+# to include it in the directory name.
+mv linux-* linux-${PACKAGE_VERSION} 2> /dev/null
+ln -sf linux-* linux
+
 mkdir $PKG/install
 cat $CWD/slack-desc/slack-desc.kernel-source > $PKG/install/slack-desc
 
-# Make the package:
+# Make the package: (also no $LOCALVERSION here)
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/kernel-source-$(echo ${PACKAGE_VERSION} | tr - _)$(echo ${LOCALVERSION} | tr - _)-noarch-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/kernel-source-$(echo ${PACKAGE_VERSION} | tr - _)-noarch-$BUILD.txz
