Fri Sep 20 19:25:40 UTC 2024
a/dracut-103-x86_64-2.txz:  Rebuilt.
  Include /etc/dracut.conf.d/elogind.conf to handle uaccess rules correctly.
  Thanks to LuckyCyborg.
l/cairo-1.18.2-x86_64-2.txz:  Rebuilt.
  [PATCH] cff: Don't fail if no local subs.
  Fixes printing PDFs with CUPS. Thanks to pee_bee and reddog83.
l/glib2-2.82.1-x86_64-1.txz:  Upgraded.
l/pipewire-1.2.4-x86_64-1.txz:  Upgraded.
n/NetworkManager-1.48.10-x86_64-2.txz:  Rebuilt.
  Rebuilt to pick up the new plugin directory for ppp-2.5.1.
n/bind-9.20.2-x86_64-1.txz:  Upgraded.
n/openssh-9.9p1-x86_64-1.txz:  Upgraded.
  Future deprecation notice: OpenSSH plans to remove support for the DSA
  signature algorithm in early 2025. For now, this package retains DSA
  support, but plan accordingly.
n/ppp-2.5.1-x86_64-1.txz:  Upgraded.
n/rp-pppoe-4.0-x86_64-1.txz:  Upgraded.
  Upstream has removed "ancient crufty scripts," so see HOW-TO-CONNECT in the
  documentation if you were using those to connect previously.

diff --git a/source/n/ppp/ppp.SlackBuild b/source/n/ppp/ppp.SlackBuild
--- a/source/n/ppp/ppp.SlackBuild
+++ b/source/n/ppp/ppp.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2013, 2015, 2018, 2020, 2021  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2013, 2015, 2018, 2020, 2021, 2024  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,17 +23,17 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=ppp
-VERSION=2.4.9
+VERSION=2.5.1
 RADVER=1.1.7
 PPPVER=1.98
-BUILD=${BUILD:-4}
+BUILD=${BUILD:-1}
 
 NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i586 ;;
+    i?86) export ARCH=i686 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
@@ -74,38 +74,37 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
 
-zcat $CWD/ppp.slack.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
 sed -i -e "s#lib/pppd#lib${LIBDIRSUFFIX}/pppd#g" $(grep -lr 'lib/pppd' *)
 
-# This conflicts with the header in 3.5+ kernels:
-rm -f include/linux/if_pppol2tp.h
-
-zcat $CWD/ppp.CVE-2015-3310.diff.gz | patch -p1 --verbose || exit 1
-
-cat $CWD/ppp.gcc14.diff | patch -p1 --verbose || exit 1
-
-# Choose correct options depending on whether PAM is installed:
-if [ -L /lib${LIBDIRSUFFIX}/libpam.so.? ]; then
-  PAM_OPTIONS="USE_PAM=y"
-else
-  unset PAM_OPTIONS
+# Configure, build, and install:
+if [ ! -r configure ]; then
+  if [ -x ./autogen.sh ]; then
+    NOCONFIGURE=1 ./autogen.sh
+  else
+    autoreconf -vif
+  fi
 fi
-
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} || exit 1
-
-make $PAM_OPTIONS $NUMJOBS || make $PAM_OPTIONS || exit 1
-make $PAM_OPTIONS install DESTDIR=$PKG/usr || exit 1
-
-if [ ! -z "$PAM_OPTIONS" ]; then
-  mkdir -p $PKG/etc/pam.d
-  cat pppd/ppp.pam > $PKG/etc/pam.d/ppp.new
-fi
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --docdir=/usr/doc/$PKGNAM-$VERSION \
+  --mandir=/usr/man \
+  --infodir=/usr/info \
+  --disable-static \
+  --build=$ARCH-slackware-linux || exit 1
+make $NUMJOBS || make || exit 1
+make install DESTDIR=$PKG || exit 1
 
 # Install PPP config files:
-mkdir -p $PKG/etc/ppp
+rm -f $PKG/etc/ppp/*
 cp -a etc.ppp/* $PKG/etc/ppp
+for file in $PKG/etc/ppp/*.example ; do
+  mv $file $(dirname $file)/$(basename $file .example)
+done
 chmod 600 $PKG/etc/ppp/*secrets
 ( cd $PKG/etc/ppp
   mv chap-secrets chap-secrets.new
@@ -113,22 +112,21 @@ chmod 600 $PKG/etc/ppp/*secrets
   mv pap-secrets pap-secrets.new
 )
 zcat $CWD/options.new.gz > $PKG/etc/ppp/options.new
+mkdir -p $PKG/etc/pam.d
+cat pppd/ppp.pam > $PKG/etc/pam.d/ppp.new
 
-# Fix what seems like an insecure default setting.
-# Feel free to "chmod 4750 pppoatm.so rp-pppoe.so" at your own risk.
-# Since they are only runnable by group root, the risk really isn't much...
-chmod 755 $PKG/usr/lib${LIBDIRSUFFIX}/pppd/*/*.so
-
-# The Makefile doesn't error out if building rp-pppoe.so fails, so check for it:
-if [ ! -r $PKG/usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so ]; then
-  echo "FATAL: /usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so failed to build."
+# The Makefile doesn't error out if building pppoe.so fails, so check for it:
+if [ ! -r $PKG/usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/pppoe.so ]; then
+  echo "FATAL: /usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/pppoe.so failed to build."
   exit 1
 fi
 
 mkdir -p $PKG/usr/doc/ppp-$VERSION
 cp -a \
-  FAQ PLUGINS README* SETUP scripts \
+  AUTHORS* COPYING* ChangeLog* FAQ* LICENSE* NEWS* PLUGINS* README* SECURITY* SETUP* Submitting-patches* \
+  scripts \
   $PKG/usr/doc/ppp-$VERSION
+rm -f $PKG/usr/doc/ppp-$VERSION/scripts/Makefile*
 
 echo "+====================+"
 echo "| freeradius-client-$RADVER |"
@@ -182,7 +180,7 @@ cp -a \
   $PKG/usr/doc/pppsetup
 
 # Don't ship .la files:
-rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+find $PKG -name "*.la" -exec rm -f "{}" \;
 
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
